name: Flask Automated Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "SSH key configured."

      - name: Set Environment Variables
        run: |
          echo "HOST_NAME=34.236.156.157" >> $GITHUB_ENV
          echo "Configured environment variables."

      - name: Display Configured Host Name
        run: echo "The configured host name is $HOST_NAME"

      - name: Execute SSH Commands
        env:
          USER_NAME: ubuntu
        run: |
          cat /home/runner/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $USER_NAME@$HOST_NAME "cd NewsApi && git pull && sudo systemctl restart newsapi.service"
          echo "Commands executed via SSH."
