

name: Flask Automated Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute SSH Commands
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          echo "Debug: Attempting to connect to $HOST_NAME with user $USER_NAME"
          ssh -vvv -o StrictHostKeyChecking=no -i <(echo "$SSH_PRIVATE_KEY") $USER_NAME@$HOST_NAME "echo 'Connection Successful'"
