name: Flask Automated Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push to EC2
        env:
          PRIVATE_ENV: ${{secrets.PRIVATE_KEY}}
          HOST_NAME: ${{secrets.HOST_NAME}}
          USER_NAME: ${{secrets.USER_NAME}}
        run: |
          echo "$PRIVATE_ENV" > private_key && chmod 600 private_key
          ssh -o StrictHostChecking=no -i private_key $USER_NAME 'cd NewsApi && git pull && sudo systemctl restart newsapi.service'
