

name: Flask Automated Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > ~/ssh_key
          chmod 600 ~/ssh_key

      - name: Set color
        id: color-selector
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"

      # - name: Execute SSH Commands
      #   env:
      #     HOST_NAME: ${{ secrets.HOST_NAME }}
      #     USER_NAME: ${{ secrets.USER_NAME }}
      #   run: |
      #     echo "Connecting to $USER_NAME@$HOST_NAME"
      #     ssh -vvv -o StrictHostKeyChecking=no -i ~/ssh_key $USER_NAME@$HOST_NAME "cd NewsApi && git pull && sudo systemctl restart newsapi.service"
