

name: Flask Automated Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        env:
          PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEAhz+Xup5PQc183MtWC4x6TZROYS8CRjEOWIdcXh/Fka07u/ck
AoHpllGUknnwjr6OClWoCH8qHSz8tv+ojttm+R/rh2J4CYegH/gGvHVAvYZ2DNvr
rGK0xrbCAg9dB7aokaevSHRimz+EY84MiH4rqJjPrXsVvejrwfcqHBgGTyofbglL
zz0DJTn4ukXBQ1OqlKVOzOac2UWNcpsYy5eNFo3FPvmb0Ibu7rDJr7MDylr1PMb6
5iFmvBsPHRe7ZGXS81IHuELeu9VMDmsy3WFzlBLsQLNOhW1pWTcdQhTjXyEtnOXj
RjOcNVyq4GZyrXUgJLpuA8hAlORmYyc1UV4EnQIDAQABAoH/c7LzGbJUGvau2jMY
aMjD15oHcxvD1kgg/ZrOabbETNrlPucs5vg721vuvV+TaomY+T5NgPdID61sgyAy
EgOfE386/ZY/GefsE20aVh34RCnC0z1PXykRfOzbCugZrX+UtQW97T2jHSw5FSgv
kJRexNv0zXN+JfgbttK6M05aF12y+WiR+nypq1X0vCLuhkUdV/d2bOZTZFW1oul5
Z425k4xy1jSmJth4pCJnFxPAo0fXKBut6T5TlWu/OisS0OXSrrzrXumFOmpmPrnA
kZWxhzum1x2q70GakkF/+oCMiZlz6rTMMETdaS2Hn0qmH3yRArA64EJKIVsyGGiN
1a21AoGBAMCKFAJTHN8fFSWsKbDmHL+QS/M/BEnWgAX7lSLUv53R7RO8WPQYPl7Y
8YzzH6zG9yZPKRpQ85Z3/m1EUZ5x/11lTu8EVvtF8xyYZAAbPpe66drdPzEMnxrT
121+pCs7FDVjdo8jJVakT1JRBKhv6HhDfJd40zBsyos5N/J41fKHAoGBALPTd5Kt
J5LkPvq3f9B33VSslTNaBtpEoSxSDy7fbpPwJMFs0lomwWfFjOvRDkN5akNP3lx4
C6LhC+Fho9ysS/7P/IxNQC4b8vxsh8k1d+K62om0YfyuqpvfjAX94qjl7EAYhLQd
IhTYTuBkVvPWhgFO0y65JMvnDckaCDgKhkS7AoGBAKabVPEmBke0V9I/hdwDY0EI
lhAoqYdTS3jh2I1JV34zV1jKlJa0G9RrGaoD/5a8nMTTnxeckQvVTZ4zjgTzVCv3
LDR7puDMCLDn1TCaYrFdFltDNBk3eL34LeQbv+eAud3w8XiuyvKMP+9VGBjArYLT
sw5HiUfP+/w5SQZSNaAlAoGBAK1ZBMNYN/XaIPv/OC713V5qn8lI16JA1j2rPQeq
SyZBMK1lAcH16irmvNn2RRG2UUFiFLB+6HizCIjTXuqzDO8t//4f2eaY+rtqw9qq
uE7QYSqtwGec2Mo5zPlZrM20FvISsJoQG3KMsjyNfWTBP5yzJ9C6mUYWDav2dEXR
n21RAoGAMbA8AR0mTYeBwtF9+6Adr0RztCDPwVFBtzWuYEDs8spvAuKY0w2egcdo
U0zrKip/AiNx914DTCrqZjwuamjFQL0GqoWb9wtOaF8ZBAitbebz12gXOLpwGUwV
w7fw+tlqjfu6AdWZCMCuPICRL6Ax1RJzGGZfVzOy87lkhCJk/X8=
-----END RSA PRIVATE KEY-----"
        run: |
          echo "$PRIVATE_KEY" > ~/ssh_key
          chmod 600 ~/ssh_key

      - name: Set color
        id: color-selector
        env:
          HOST_NAME: 34.236.156.157
        run: echo "SELECTED_COLOR=$HOST_NAME" >> "$GITHUB_OUTPUT"
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"

      # - name: Execute SSH Commands
      #   env:
      #     HOST_NAME: ${{ secrets.HOST_NAME }}
      #     USER_NAME: ${{ secrets.USER_NAME }}
      #   run: |
      #     echo "Connecting to $USER_NAME@$HOST_NAME"
      #     ssh -vvv -o StrictHostKeyChecking=no -i ~/ssh_key $USER_NAME@$HOST_NAME "cd NewsApi && git pull && sudo systemctl restart newsapi.service"
